services:
    traefik:
        image: traefik:v2.9
        container_name: traefik_website
        command:
            - "--log.level=DEBUG"
            - "--entrypoints.web.address=:${PUBLIC_PORT}"
            - "--api.insecure=true"
            - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
            - "--certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
            - "--providers.file.directory=/configuration/"
            - "--providers.file.watch=true"
            - "--accesslog=true"
            - "--accesslog.filePath=/logs/access.log"
        ports:
            - ${BIND_INTERFACE}:${PUBLIC_PORT}:${PUBLIC_PORT}
        env_file:
            - .env
        volumes:
            - letsencrypt:/letsencrypt:rw
            - ./dynamic.yml:/configuration/dynamic.yml:ro
        read_only: true
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE
        security_opt:
            - "no-new-privileges:true"

    shlink_api:
        container_name: shlink_api
        image: shlinkio/shlink:stable
        restart: always
        environment:
            DEFAULT_DOMAIN: "${PUBLIC_SHLINK_API_HOST}"
            IS_HTTPS_ENABLED: "${USE_TLS}"
            INITIAL_API_KEY: "${SHLINK_SERVER_API_KEY}"
            GEOLITE_LICENSE_KEY: "${SHLINK_GEOLITE_LICENSE_KEY}"
            DB_DRIVER: postgres
            DB_HOST: shlink_db
            DB_USER: "${SHLINK_DB_USER}"
            DB_PASSWORD: "${SHLINK_DB_PASSWORD}"
        depends_on:
            - shlink_db

    shlink_db:
        container_name: shlink_db
        image: postgres:15.1-alpine
        restart: always
        environment:
            POSTGRES_USER: "${SHLINK_DB_USER}"
            POSTGRES_PASSWORD: "${SHLINK_DB_PASSWORD}"
            POSTGRES_DB: "${SHLINK_DB_NAME}"
        volumes:
            - ./data/database:/var/lib/postgresql/data:rw
        user: ${DOCKER_UID}:${DOCKER_GID}

    shlink_client:
        container_name: shlink_client
        image: shlinkio/shlink-web-client:latest
        restart: always
        environment:
            SHLINK_SERVER_URL: "${SHLINK_SERVER_URL}"
            SHLINK_SERVER_API_KEY: "${SHLINK_SERVER_API_KEY}"
            SHLINK_SERVER_NAME: "Shlink"

volumes:
    letsencrypt:
